flowchart TD
    get[GetUser Method]
    id[UserID]
    repo[(Repository)]
    user[UserModelDTO]
    resMap(UserResponseFormatter)
    resDTO[UserResponseDTO]
    nfError([NotFoundError])

    get --> id
    id --> repo
    repo -- Is Found --> user
    repo -- Is Not Found --> nfError
    user --> resMap
    resMap --> resDTO