flowchart TD
    classDef input fill:#007bff,color:#fff
    classDef output fill:#23e837,color:#fff
    classDef error fill:#e31919,color:#fff

    classDef dependence stroke:#eeff00

    id([Params ID])
    query[(Repository)]
    found[Founded User]
    nfError([Not Found Error])
    resMap(Response Formatter)
    resDTO([Formatted Response])

    class id input
    class resDTO output
    class nfError error

    class query dependence
    class resMap dependence

    id -- Read Query --> query
    query -- Returns --> found
    found -- Is Defined --> resMap
    found -- Is Null --> nfError
    resMap -- Returns --> resDTO